[package]
name = "bit-journal-cli"
version = "0.1.0"
authors = ["Blaine Price <1wbprice@gmail.com>"]
edition = "2018"

[dependencies]
termion = "1.5.3"
chrono = "0.4"
structopt = "0.3.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8"
